title: Maya Gillilan # your name (or website title) here
logo: "/images/paszport usa.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  BEng Computer Science student, Łódź University of Technology, with a focus on machinelearning, human computer interaction, and ubiquitous computing
  <br><br>
  <a href="https://www.linkedin.com/in/maya-gillilan-97ab58201/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
